doctrine:
    dbal:
        dbname:               swapi
        host:                 localhost
        port:                 3306
        user:                 root
        password:             test
        driver:               pdo_mysql
        # if the url option is specified, it will override the above config
        url:                  mysql://root:test@localhost:3306/swapi
        server_version:       'mariadb-10.1.34'
        # the DBAL driverClass option
        driver_class:         App\DBAL\MyDatabaseDriver
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
