starwars_list:
    path:       /starwars
    controller: App\Controller\starwarsController::list

starwars_jedi_characters:
    path:       /starwars/jedi/characters
    controller: App\Controller\starwarsController::getJediCharacters

starwars_species_mammal:
    path:       /starwars/species/mammal
    controller: App\Controller\starwarsController::getMammalSpecies

import_characters:
    path:       /starwars/characters/import
    controller: App\Controller\starwarsController::importCharacters

update_characters:
    path:       /starwars/characters/update
    controller: App\Controller\starwarsController::updateCharacters